import pprint
# Maintenance examples 

maintenance_example_one = {'message': {'code': 0, 'message': 'ok', 'credentials': 'valid', 'version': 'v3.0.0', 'endpoint': 'maint', 'counter': 3}, 'data': [{'desc': 'Change Engine Oil and Filter', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect All Fluids and Correct Level', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 18.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 18.47}, 'parts': None}, {'desc': 'Inspect Automatic Transmission Fluid if equipped with Dipstick', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Battery Condition & Charge', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Body & Paint for Damages/Corrosion', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 6.6, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 6.6}, 'parts': None}, {'desc': 'Inspect Brake System, Friction Material and Hydraulic System.', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Cooling System, Hoses & Clamps', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect CV Joints and Boots.', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 77.63, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 77.63}, 'parts': None}, {'desc': 'Inspect Engine & Motor/Electronics Cooling System & Hoses', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Exhaust System , Catalytic Converter and Heat Shield', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Horn, Lights, A/C & Heater For Proper Operation', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 35.2, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 35.2}, 'parts': None}, {'desc': 'Inspect Intake System & Engine Air Filter', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Interior/Exterior Lights & Electrical Components', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 20.48, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 20.48}, 'parts': None}, {'desc': 'Inspect Parking Brake Operation & Tension', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 87.96, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 87.96}, 'parts': None}, {'desc': 'Inspect Radiator and Condenser', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Seat Belts & Related Components', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Undercarriage For Leaks, Damage, and Corrosion', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 23.25, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 23.25}, 'parts': None}, {'desc': 'Inspect Warning System Operation', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Weatherstripping', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Wheels For End Play & Noise', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 169.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 169.47}, 'parts': None}, {'desc': 'Inspect Windshield', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Wiper & Washer System', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 18.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 18.47}, 'parts': None}, {'desc': 'Lube Lock Cylinders, Latches, Hinges & Pivots', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.3, 'labor_rate_per_hour': 101.44, 'part_cost': 7.81, 'labor_cost': 30.43, 'misc_cost': 25.0, 'total_cost': 63.24}, 'parts': [{'desc': 'Multi Purpose Lubricant', 'manufacturer': '', 'price': 7.81, 'qty': 1}]}, {'desc': 'Measure Brake Linings, Rotor Thickness and Runout', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.3, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 30.43, 'misc_cost': 25.0, 'total_cost': 55.43}, 'parts': None}, {'desc': 'Rotate Tires, Inspect Tire Wear, and Adjust Tire Pressure.', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.5, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 50.72, 'misc_cost': 25.0, 'total_cost': 75.72}, 'parts': None}, {'desc': 'Replace Cabin Air Filter', 'due_mileage': 40000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Change Engine Oil and Filter', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect All Fluids and Correct Level', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 18.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 18.47}, 'parts': None}, {'desc': 'Inspect Automatic Transmission Fluid if equipped with Dipstick', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Battery Condition & Charge', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Body & Paint for Damages/Corrosion', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 6.6, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 6.6}, 'parts': None}, {'desc': 'Inspect Brake System, Friction Material and Hydraulic System.', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Cooling System, Hoses & Clamps', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect CV Joints and Boots.', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 77.63, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 77.63}, 'parts': None}, {'desc': 'Inspect Engine & Motor/Electronics Cooling System & Hoses', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Exhaust System , Catalytic Converter and Heat Shield', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Horn, Lights, A/C & Heater For Proper Operation', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 35.2, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 35.2}, 'parts': None}, {'desc': 'Inspect Intake System & Engine Air Filter', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Interior/Exterior Lights & Electrical Components', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 20.48, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 20.48}, 'parts': None}, {'desc': 'Inspect Parking Brake Operation & Tension', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 87.96, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 87.96}, 'parts': None}, {'desc': 'Inspect Radiator and Condenser', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Seat Belts & Related Components', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 0, 'repair_hours': 0.0, 'labor_rate_per_hour': 0.0, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Undercarriage For Leaks, Damage, and Corrosion', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 23.25, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 23.25}, 'parts': None}, {'desc': 'Inspect Warning System Operation', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Weatherstripping', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Wheels For End Play & Noise', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 169.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 169.47}, 'parts': None}, {'desc': 'Inspect Windshield', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 0.0}, 'parts': None}, {'desc': 'Inspect Wiper & Washer System', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.0, 'labor_rate_per_hour': 101.44, 'part_cost': 18.47, 'labor_cost': 0.0, 'misc_cost': 0.0, 'total_cost': 18.47}, 'parts': None}, {'desc': 'Lube Lock Cylinders, Latches, Hinges & Pivots', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 1, 'repair_hours': 0.3, 'labor_rate_per_hour': 101.44, 'part_cost': 7.81, 'labor_cost': 30.43, 'misc_cost': 25.0, 'total_cost': 63.24}, 'parts': [{'desc': 'Multi Purpose Lubricant', 'manufacturer': '', 'price': 7.81, 'qty': 1}]}, {'desc': 'Measure Brake Linings, Rotor Thickness and Runout', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.3, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 30.43, 'misc_cost': 25.0, 'total_cost': 55.43}, 'parts': None}, {'desc': 'Rotate Tires, Inspect Tire Wear, and Adjust Tire Pressure.', 'due_mileage': 50000, 'due_km': 0, 'is_oem': True, 'repair': {'repair_difficulty': 2, 'repair_hours': 0.5, 'labor_rate_per_hour': 101.44, 'part_cost': 0.0, 'labor_cost': 50.72, 'misc_cost': 25.0, 'total_cost': 75.72}, 'parts': None}]}
maintenance_example_two = {'data': [{'desc': 'Change Engine Oil and Filter',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Brake System, Friction Material and Hydraulic '
                   'System.',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect CV Joints and Boots.',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 51.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 51.0}},
          {'desc': 'Inspect Engine Valve Clearances',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Exhaust System',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Horn, Lights, A/C & Heater For Proper Operation',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 24.12,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 24.12}},
          {'desc': 'Inspect Interior/Exterior Lights & Electrical Components',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 7.48,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 7.48}},
          {'desc': 'Inspect Parking Brake Operation & Tension',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wiper & Washer System',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.52,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 5.52}},
          {'desc': 'Rotate Tires, Inspect Tire Wear, and Adjust Tire Pressure.',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 50.72,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.5,
                      'total_cost': 75.72}},
          {'desc': 'Inspect All Fluids and Correct Level',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.52,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 5.52}},
          {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Fuel System',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.63,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 5.63}},
          {'desc': 'Inspect Tie-Rod Ends, Steering Gear & Boots',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 33.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 33.0}},
          {'desc': 'Inspect Tire Sealant Expiration Date',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 63.38,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 63.38}},
          {'desc': 'Measure Brake Linings, Rotor Thickness and Runout',
           'due_km': 0,
           'due_mileage': 100000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 30.43,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.3,
                      'total_cost': 55.43}},
          {'desc': 'Change Engine Oil and Filter',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Brake System, Friction Material and Hydraulic '
                   'System.',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect CV Joints and Boots.',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 51.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 51.0}},
          {'desc': 'Inspect Engine Valve Clearances',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Exhaust System',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Horn, Lights, A/C & Heater For Proper Operation',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 24.12,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 24.12}},
          {'desc': 'Inspect Interior/Exterior Lights & Electrical Components',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 7.48,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 7.48}},
          {'desc': 'Inspect Parking Brake Operation & Tension',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wiper & Washer System',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.52,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 5.52}},
          {'desc': 'Rotate Tires, Inspect Tire Wear, and Adjust Tire Pressure.',
           'due_km': 0,
           'due_mileage': 110000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 50.72,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.5,
                      'total_cost': 75.72}},
          {'desc': 'Change Engine Oil and Filter',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Brake System, Friction Material and Hydraulic '
                   'System.',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect CV Joints and Boots.',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 51.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 51.0}},
          {'desc': 'Inspect Engine Valve Clearances',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Exhaust System',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Horn, Lights, A/C & Heater For Proper Operation',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 24.12,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 24.12}},
          {'desc': 'Inspect Interior/Exterior Lights & Electrical Components',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 7.48,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 7.48}},
          {'desc': 'Inspect Parking Brake Operation & Tension',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wiper & Washer System',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.52,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 5.52}},
          {'desc': 'Rotate Tires, Inspect Tire Wear, and Adjust Tire Pressure.',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 50.72,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.5,
                      'total_cost': 75.72}},
          {'desc': 'Inspect All Fluids and Correct Level',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.52,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 5.52}},
          {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Fuel System',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 5.63,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 5.63}},
          {'desc': 'Inspect Tie-Rod Ends, Steering Gear & Boots',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 33.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 33.0}},
          {'desc': 'Inspect Tire Sealant Expiration Date',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 63.38,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 63.38}},
          {'desc': 'Measure Brake Linings, Rotor Thickness and Runout',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 30.43,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.3,
                      'total_cost': 55.43}},
          {'desc': 'Change Brake Fluid',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': [{'desc': 'Brake Fluid',
                      'manufacturer': '',
                      'price': 13.0,
                      'qty': 2}],
           'repair': {'labor_cost': 81.15,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 26.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.8,
                      'total_cost': 132.15}},
          {'desc': 'Replace Cabin Air Filter',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': [{'desc': 'Cabin Air Filter',
                      'manufacturer': '',
                      'price': 26.0,
                      'qty': 1}],
           'repair': {'labor_cost': 50.72,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 26.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.5,
                      'total_cost': 101.72}},
          {'desc': 'Replace Engine Air Filter',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Change CVT Fluid',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Change Engine Coolant and Motor Electronics Coolant',
           'due_km': 0,
           'due_mileage': 120000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}}],
 'message': {'code': 0,
             'counter': 5,
             'credentials': 'valid',
             'endpoint': 'maint',
             'message': 'ok',
             'version': 'v3.0.0'}}
maintenance_example_three = {'data': [{'desc': 'Change Engine Oil and Filter',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect All Fluids and Correct Level',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 18.47,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 18.47}},
          {'desc': 'Inspect Ball Joints',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Battery Performance',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Brake System, Friction Material & Hydraulic System',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 25.0}},
          {'desc': 'Inspect CV Joints & Boots',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Drive/Accessory Belts & Tension',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Engine & Motor/Electronics Cooling System & Hoses',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Exhaust System',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect For Fluid Leaks',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Interior/Exterior Lights & Electrical Components',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 40.38,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 40.38}},
          {'desc': 'Inspect Parking Brake Operation & Tension',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Seat Belts & Related Components',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wheels For End Play & Noise',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wiper & Washer System',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 18.47,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 18.47}},
          {'desc': 'Lube Lock Cylinders, Latches, Hinges & Pivots',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': [{'desc': 'Multi Purpose Lubricant',
                      'manufacturer': '',
                      'price': 7.81,
                      'qty': 1}],
           'repair': {'labor_cost': 30.43,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 7.81,
                      'repair_difficulty': 1,
                      'repair_hours': 0.3,
                      'total_cost': 63.24}},
          {'desc': 'Rotate Tires, Inspect Tire Wear, & Adjust Tire Pressure',
           'due_km': 0,
           'due_mileage': 130000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 40.57,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.4,
                      'total_cost': 65.57}},
          {'desc': 'Change Engine Oil and Filter',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect All Fluids and Correct Level',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 18.47,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 18.47}},
          {'desc': 'Inspect Ball Joints',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Battery Performance',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Brake System, Friction Material & Hydraulic System',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Chassis, Steering, Suspension & Fasteners',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.0,
                      'total_cost': 25.0}},
          {'desc': 'Inspect CV Joints & Boots',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Drive/Accessory Belts & Tension',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Engine & Motor/Electronics Cooling System & Hoses',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Exhaust System',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect For Fluid Leaks',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Interior/Exterior Lights & Electrical Components',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 40.38,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 40.38}},
          {'desc': 'Inspect Parking Brake Operation & Tension',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Seat Belts & Related Components',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wheels For End Play & Noise',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Inspect Wiper & Washer System',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 0.0,
                      'part_cost': 18.47,
                      'repair_difficulty': 1,
                      'repair_hours': 0.0,
                      'total_cost': 18.47}},
          {'desc': 'Lube Lock Cylinders, Latches, Hinges & Pivots',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': [{'desc': 'Multi Purpose Lubricant',
                      'manufacturer': '',
                      'price': 7.81,
                      'qty': 1}],
           'repair': {'labor_cost': 30.43,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 7.81,
                      'repair_difficulty': 1,
                      'repair_hours': 0.3,
                      'total_cost': 63.24}},
          {'desc': 'Rotate Tires, Inspect Tire Wear, & Adjust Tire Pressure',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 40.57,
                      'labor_rate_per_hour': 101.44,
                      'misc_cost': 25.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 2,
                      'repair_hours': 0.4,
                      'total_cost': 65.57}},
          {'desc': 'Inspect Driveshaft & Related Components',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}},
          {'desc': 'Replace Cabin Filter',
           'due_km': 0,
           'due_mileage': 140000,
           'is_oem': True,
           'parts': None,
           'repair': {'labor_cost': 0.0,
                      'labor_rate_per_hour': 0.0,
                      'misc_cost': 0.0,
                      'part_cost': 0.0,
                      'repair_difficulty': 0,
                      'repair_hours': 0.0,
                      'total_cost': 0.0}}],
 'message': {'code': 0,
             'counter': 6,
             'credentials': 'valid',
             'endpoint': 'maint',
             'message': 'ok',
             'version': 'v3.0.0'}}
maintenance_responses = [maintenance_example_one, maintenance_example_two, maintenance_example_three]


# Recall examples
recall_example_one = {'message': {'code': 0, 'message': 'ok', 'credentials': 'valid', 'version': 'v3.0.0', 'endpoint': 'recall', 'counter': 4}, 'data': [{'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2014-2015 FIESTA, 2014-2016 FUSION AND LINCOLN MKZ VEHICLES SOLD, OR EVER REGISTERED IN ALABAMA, ARKANSAS, ARIZONA, CALIFORNIA, FLORIDA, GEORGIA, HAWAII, LOUISIANA, MISSISSIPPI, NEW MEXICO, NEVADA, OKLAHOMA, OREGON, SOUTH CAROLINA, TEXAS, UTAH, WASHINGTON, PUERTO RICO, AMERICAN SAMOA, GUAM, THE NORTHERN MARIANA ISLANDS (SAIPAN), AND THE U.S. VIRGIN ISLANDS.  A COMPONENT WITHIN THE DOOR LATCHES MAY BREAK MAKING THE DOORS DIFFICULT TO LATCH AND/OR LEADING THE DRIVER OR A PASSENGER TO BELIEVE A DOOR IS SECURELY CLOSED WHEN, IN FACT, IT IS NOT.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND FORD OR LINCOLN DEALERS WILL REPLACE THE SIDE DOOR LATCHES, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 21, 2020.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 20S15.", 'consequence': 'A DOOR THAT IS NOT SECURELY LATCHED COULD OPEN WHILE THE VEHICLE IS IN MOTION, INCREASING THE RISK OF INJURY TO A VEHICLE OCCUPANT.', 'recall_date': '1/23/2020', 'campaign_number': '20V177000', 'recall_number': '57536'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2014-2015 FIESTA, 2014-2016 FUSION AND LINCOLN MKZ VEHICLES SOLD, OR EVER REGISTERED IN ALABAMA, ARKANSAS, ARIZONA, CALIFORNIA, FLORIDA, GEORGIA, HAWAII, LOUISIANA, MISSISSIPPI, NEW MEXICO, NEVADA, OKLAHOMA, OREGON, SOUTH CAROLINA, TEXAS, UTAH, WASHINGTON, PUERTO RICO, AMERICAN SAMOA, GUAM, THE NORTHERN MARIANA ISLANDS (SAIPAN), AND THE U.S. VIRGIN ISLANDS.  A COMPONENT WITHIN THE DOOR LATCHES MAY BREAK MAKING THE DOORS DIFFICULT TO LATCH AND/OR LEADING THE DRIVER OR A PASSENGER TO BELIEVE A DOOR IS SECURELY CLOSED WHEN, IN FACT, IT IS NOT.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND FORD OR LINCOLN DEALERS WILL REPLACE THE SIDE DOOR LATCHES, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 21, 2020.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 20S15.", 'consequence': 'A DOOR THAT IS NOT SECURELY LATCHED COULD OPEN WHILE THE VEHICLE IS IN MOTION, INCREASING THE RISK OF INJURY TO A VEHICLE OCCUPANT.', 'recall_date': '1/23/2020', 'campaign_number': '20V177000', 'recall_number': '57537'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2014-2015 FIESTA, 2014-2016 FUSION AND LINCOLN MKZ VEHICLES SOLD, OR EVER REGISTERED IN ALABAMA, ARKANSAS, ARIZONA, CALIFORNIA, FLORIDA, GEORGIA, HAWAII, LOUISIANA, MISSISSIPPI, NEW MEXICO, NEVADA, OKLAHOMA, OREGON, SOUTH CAROLINA, TEXAS, UTAH, WASHINGTON, PUERTO RICO, AMERICAN SAMOA, GUAM, THE NORTHERN MARIANA ISLANDS (SAIPAN), AND THE U.S. VIRGIN ISLANDS.  A COMPONENT WITHIN THE DOOR LATCHES MAY BREAK MAKING THE DOORS DIFFICULT TO LATCH AND/OR LEADING THE DRIVER OR A PASSENGER TO BELIEVE A DOOR IS SECURELY CLOSED WHEN, IN FACT, IT IS NOT.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND FORD OR LINCOLN DEALERS WILL REPLACE THE SIDE DOOR LATCHES, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 21, 2020.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 20S15.", 'consequence': 'A DOOR THAT IS NOT SECURELY LATCHED COULD OPEN WHILE THE VEHICLE IS IN MOTION, INCREASING THE RISK OF INJURY TO A VEHICLE OCCUPANT.', 'recall_date': '1/23/2020', 'campaign_number': '20V177000', 'recall_number': '57538'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2014-2015 FIESTA, 2014-2016 FUSION AND LINCOLN MKZ VEHICLES SOLD, OR EVER REGISTERED IN ALABAMA, ARKANSAS, ARIZONA, CALIFORNIA, FLORIDA, GEORGIA, HAWAII, LOUISIANA, MISSISSIPPI, NEW MEXICO, NEVADA, OKLAHOMA, OREGON, SOUTH CAROLINA, TEXAS, UTAH, WASHINGTON, PUERTO RICO, AMERICAN SAMOA, GUAM, THE NORTHERN MARIANA ISLANDS (SAIPAN), AND THE U.S. VIRGIN ISLANDS.  A COMPONENT WITHIN THE DOOR LATCHES MAY BREAK MAKING THE DOORS DIFFICULT TO LATCH AND/OR LEADING THE DRIVER OR A PASSENGER TO BELIEVE A DOOR IS SECURELY CLOSED WHEN, IN FACT, IT IS NOT.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND FORD OR LINCOLN DEALERS WILL REPLACE THE SIDE DOOR LATCHES, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 21, 2020.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 20S15.", 'consequence': 'A DOOR THAT IS NOT SECURELY LATCHED COULD OPEN WHILE THE VEHICLE IS IN MOTION, INCREASING THE RISK OF INJURY TO A VEHICLE OCCUPANT.', 'recall_date': '1/23/2020', 'campaign_number': '20V177000', 'recall_number': '57539'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2013-2016 FORD FUSION AND LINCOLN MKZ, 2015-2016 FORD EDGE, AND 2016 LINCOLN MKX VEHICLES ORIGINALLY SOLD, OR CURRENTLY REGISTERED IN CONNECTICUT, DELAWARE, THE DISTRICT OF COLUMBIA, ILLINOIS, INDIANA, IOWA, MAINE, MARYLAND, MASSACHUSETTS, MICHIGAN, MINNESOTA, MISSOURI, NEW HAMPSHIRE, NEW JERSEY, NEW YORK, OHIO, PENNSYLVANIA, RHODE ISLAND, VERMONT, WEST VIRGINIA, AND WISCONSIN.  ROAD SALT OR OTHER CONTAMINANTS MAY CORRODE THE ELECTRIC POWER STEERING GEAR MOTOR ATTACHMENT BOLTS.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPLACE THE STEERING GEAR MOTOR BOLTS AND APPLY A WAX SEALER.  IF ANY OF THE STEERING GEAR MOTOR ATTACHMENT BOLTS ARE BROKEN OR MISSING, A NEW STEERING GEAR WILL BE INSTALLED IN THE VEHICLE.  THESE REPAIRS WILL BE PERFORMED FREE OF CHARGE. THE RECALL BEGAN OCTOBER 18, 2019.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 19S26.", 'consequence': 'IF THE BOLTS CORRODE, THE STEERING GEAR MOTOR MAY DETACH FROM THE GEAR HOUSING RESULTING IN A LOSS OF POWER STEERING ASSIST, REQUIRING A GREATER STEERING EFFORT, ESPECIALLY AT LOWER SPEEDS, AND INCREASING THE RISK OF A CRASH.', 'recall_date': '1/29/2019', 'campaign_number': '19V632000', 'recall_number': '57530'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2013-2016 FUSION VEHICLES EQUIPPED WITH 2.5 LITER ENGINES.  THE BUSHING THAT ATTACHES THE TRANSMISSION SHIFTER CABLE TO THE TRANSMISSION MAY DEGRADE OVER TIME AND CAUSE THE BUSHING TO DETACH FROM THE TRANSMISSION.  THE CONDITION COULD ALLOW THE DRIVER TO MOVE THE SHIFT LEVER TO PARK AND REMOVE THE IGNITION KEY, WHILE THE TRANSMISSION MAY NOT BE IN PARK, WITH NO WARNING MESSAGE OR AUDIBLE CHIME.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPLACE THE SHIFTER CABLE BUSHING, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 10, 2019.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 19S16.  NOTE: OWNERS ARE DIRECTED TO USE THE PARKING BRAKE UNTIL THE RECALL REMEDY REPAIRS CAN BE MADE.  THIS RECALL IS AN EXPANSION OF 18V471.", 'consequence': 'IF THE VEHICLE IS EXITED WITHOUT THE TRANSMISSION BEING IN PARK AND WITHOUT THE PARKING BRAKE BEING APPLIED, THE VEHICLE MAY UNEXPECTEDLY MOVE, INCREASING THE RISK OF A CRASH.', 'recall_date': '1/13/2019', 'campaign_number': '19V362000', 'recall_number': '57531'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2013-2014 FORD ESCAPE, AND 2013-2016 FORD FUSION VEHICLES, EQUIPPED WITH SIX-SPEED AUTOMATIC TRANSMISSIONS.  THE BUSHING THAT ATTACHES THE TRANSMISSION SHIFTER CABLE TO THE TRANSMISSION MAY DEGRADE OVER TIME AND CAUSE THE BUSHING TO DETACH FROM THE TRANSMISSION.  THE CONDITION COULD ALLOW THE DRIVER TO MOVE THE SHIFT LEVER TO PARK AND REMOVE THE IGNITION KEY, WHILE THE TRANSMISSION MAY NOT BE IN PARK, WITH NO WARNING MESSAGE OR AUDIBLE CHIME.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPLACE THE SHIFTER CABLE BUSHING, FREE OF CHARGE.  THE RECALL BEGAN SEPTEMBER 20, 2018.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 18S20.  NOTE: OWNERS ARE DIRECTED TO USE THE PARKING BRAKE UNTIL THE RECALL REMEDY REPAIRS CAN BE MADE.", 'consequence': 'IF THE VEHICLE IS EXITED WITHOUT THE TRANSMISSION BEING IN PARK AND WITHOUT THE PARKING BRAKE BEING APPLIED, THE VEHICLE MAY UNEXPECTEDLY MOVE, INCREASING THE RISK OF A CRASH.', 'recall_date': '1/16/2018', 'campaign_number': '18V471000', 'recall_number': '57540'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN 2014-2018 LINCOLN MKZ AND FORD FUSION VEHICLES.  THE STEERING WHEEL RETAINING BOLT MAY LOOSEN ALLOWING THE STEERING WHEEL TO DETACH WHILE DRIVING.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPLACE THE STEERING WHEEL BOLT WITH A LONGER BOLT, FREE OF CHARGE.   OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 18S08.", 'consequence': 'A STEERING WHEEL DETACHMENT CAN CAUSE A LOSS OF STEERING CONTROL, INCREASING THE RISK OF A CRASH.', 'recall_date': '1/12/2018', 'campaign_number': '18V167000', 'recall_number': '57541'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2013-2016 FORD FUSION VEHICLES MANUFACTURED NOVEMBER 2, 2012, TO JULY 31, 2014, AND 2013-2015 LINCOLN MKZ VEHICLES MANUFACTURED NOVEMBER 14, 2012, TO JULY 31, 2014.  IN THE EVENT OF A CRASH, HEAT FROM THE DEPLOYMENT OF A SEAT BELT PRETENSIONER MAY CAUSE A FRONT SEAT BELT ANCHOR CABLE TO FAIL.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL APPLY A PROTECTIVE COATING TO THE SEAT BELT CABLE, FREE OF CHARGE.  THE RECALL BEGAN MAY 16, 2017.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 16S42.", 'consequence': 'IF THE DRIVER OR FRONT PASSENGER SEATBELT CABLES CANNOT PROPERLY RESTRAIN THE FRONT SEAT OCCUPANTS, THEY WOULD BE AT AN INCREASED RISK OF INJURY.', 'recall_date': '1/5/2016', 'campaign_number': '16V875000', 'recall_number': '57533'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2016 FORD FUSION VEHICLES MANUFACTURED FROM MARCH 10, 2016, THROUGH MARCH 16, 2016.  THE FRONT DRIVER SEAT TRACK ASSEMBLY\'S REAR RISER MAY HAVE BEEN IMPROPERLY WELDED TO THE SEAT TRACK RAIL, AND AS A RESULT, THE DRIVER MAY NOT BE ADEQUATELY RESTRAINED IN A CRASH.  AS SUCH, THESE VEHICLES FAIL TO COMPLY WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD (FMVSS) NUMBERS 207, "SEATING SYSTEMS" AND 210, "SEAT BELT ASSEMBLY ANCHORAGES."', 'corrective_action': "FORD QUARANTINED THE AFFECTED VEHICLES AT DEALERSHIPS PRIOR TO THEIR SALE.  DEALERS WILL REPLACE THE FRONT DRIVER SEAT TRACK RAIL, FREE OF CHARGE.  THE RECALL BEGAN ON MAY 19, 2016.  FORD'S NUMBER FOR THIS RECALL IS 16C05.", 'consequence': 'AN IMPROPERLY WELDED DRIVER SEAT RISER MAY FAIL TO ADEQUATELY RESTRAIN THE DRIVER DURING CRASH, INCREASING THE RISK OF INJURY.', 'recall_date': '1/27/2016', 'campaign_number': '16V250000', 'recall_number': '57534'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2016 FORD FUSION VEHICLES MANUFACTURED FROM MARCH 10, 2016, THROUGH MARCH 16, 2016.  THE FRONT DRIVER SEAT TRACK ASSEMBLY\'S REAR RISER MAY HAVE BEEN IMPROPERLY WELDED TO THE SEAT TRACK RAIL, AND AS A RESULT, THE DRIVER MAY NOT BE ADEQUATELY RESTRAINED IN A CRASH.  AS SUCH, THESE VEHICLES FAIL TO COMPLY WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD (FMVSS) NUMBERS 207, "SEATING SYSTEMS" AND 210, "SEAT BELT ASSEMBLY ANCHORAGES."', 'corrective_action': "FORD QUARANTINED THE AFFECTED VEHICLES AT DEALERSHIPS PRIOR TO THEIR SALE.  DEALERS WILL REPLACE THE FRONT DRIVER SEAT TRACK RAIL, FREE OF CHARGE.  THE RECALL BEGAN ON MAY 19, 2016.  FORD'S NUMBER FOR THIS RECALL IS 16C05.", 'consequence': 'AN IMPROPERLY WELDED DRIVER SEAT RISER MAY FAIL TO ADEQUATELY RESTRAIN THE DRIVER DURING CRASH, INCREASING THE RISK OF INJURY.', 'recall_date': '1/27/2016', 'campaign_number': '16V250000', 'recall_number': '57535'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2016 FORD FUSION VEHICLES MANUFACTURED SEPTEMBER 3, 2015, TO SEPTEMBER 13, 2015, AND 2016 LINCOLN MKZ VEHICLES MANUFACTURED SEPTEMBER 3, 2015, TO SEPTEMBER 12, 2015.  THE AFFECTED VEHICLES HAVE A FUEL TANK THAT MAY HAVE INSUFFICENT WALL THICKNESS.  AS A RESULT, THE FUEL TANKS MAY CRACK IN THE EVENT OF A CRASH AND THUS THE VEHICLES FAIL TO COMPLY WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD (FMVSS) NUMBER 301, "FUEL SYSTEM INTEGRITY."', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPLACE THE FUEL TANK, FREE OF CHARGE.  THE RECALL BEGAN ON OCTOBER 19, 2015.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 15C11.", 'consequence': 'A FUEL TANK THAT CRACKS MAY LEAK FUEL, INCREASING THE RISK OF A FIRE.', 'recall_date': '1/1/2015', 'campaign_number': '15V618000', 'recall_number': '57532'}]}
recall_example_two = {'message': {'code': 0, 'message': 'ok', 'credentials': 'valid', 'version': 'v3.0.0', 'endpoint': 'recall', 'counter': 7}, 'data': [{'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2001-2008 FORD ESCAPE AND MERCURY MARINER VEHICLES MANUFACTURED MARCH 31, 2001, TO SEPTEMBER 1, 2009.  THE AFFECTED VEHICLES ARE EQUIPPED WITH EITHER A 2.3L OR 3.0L ENGINE AND HAVE HAD THEIR CD4E TRANSMISSION REPLACED WITH REMANUFACTURED ONE THAT WAS REBUILT BETWEEN JUNE 11, 2015 THROUGH JULY 15, 2015.  THESE SERVICE REPAIR PART TRANSMISSIONS HAVE A SHIFT LEVER BOLT THAT MAY NOT BE PROPERLY TIGHTENED.  AS A RESULT, THE SHIFT CONTROL LEVER COULD DISENGAGE FROM THE TRANSMISSION WITHOUT WARNING. ', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL INSPECT THE TRANSMISSIONS AND EITHER TIGHTEN THE MANUAL SHIFT LEVER BOLT OR REPLACE THE MANUAL SHIFT LEVER ASSEMBLY.  THESE REPAIRS WILL BE PERFORMED FREE OF CHARGE.  THE RECALL BEGAN ON OCTOBER 23, 2015.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 15S28. ", 'consequence': 'IF THE SHIFT LEVER DISENGAGES FROM THE TRANSMISSION, A DRIVER MAY BE UNABLE TO SHIFT GEAR POSITIONS AND THE INDICATED SHIFT POSITION MAY NOT REPRESENT THE GEAR POSITION THE VEHICLE IS IN.  SHOULD A DISENGAGEMENT OCCUR WHILE THE VEHICLE IS BEING DRIVEN, WHEN THE DRIVER GOES TO STOP AND PARK THE VEHICLE, THE GEAR SELECTION INDICATOR MAY SHOW THAT THE TRANSMISSION IS IN THE "PARK" POSITION, BUT THE VEHICLE TRANSMISSION MAY NOT ACTUALLY BE IN THE "PARK" GEAR POSITION.  IF THE VEHICLE IS NOT IN THE "PARK" POSITION THERE IS A RISK THE VEHICLE WILL ROLL AWAY AS THE DRIVER AND OTHER OCCUPANTS EXIT THE VEHICLE OR ANYTIME THEREAFTER.  A VEHICLE ROLLAWAY INCREASES THE RISK OF INJURY TO EXITING OCCUPANTS AND BYSTANDERS.', 'recall_date': '1/29/2015', 'campaign_number': '15V606000', 'recall_number': '53492'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2001-2008 FORD ESCAPE AND MERCURY MARINER VEHICLES MANUFACTURED MARCH 31, 2001, TO SEPTEMBER 1, 2009.  THE AFFECTED VEHICLES ARE EQUIPPED WITH EITHER A 2.3L OR 3.0L ENGINE AND HAVE HAD THEIR CD4E TRANSMISSION REPLACED WITH REMANUFACTURED ONE THAT WAS REBUILT BETWEEN JUNE 11, 2015 THROUGH JULY 15, 2015.  THESE SERVICE REPAIR PART TRANSMISSIONS HAVE A SHIFT LEVER BOLT THAT MAY NOT BE PROPERLY TIGHTENED.  AS A RESULT, THE SHIFT CONTROL LEVER COULD DISENGAGE FROM THE TRANSMISSION WITHOUT WARNING. ', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL INSPECT THE TRANSMISSIONS AND EITHER TIGHTEN THE MANUAL SHIFT LEVER BOLT OR REPLACE THE MANUAL SHIFT LEVER ASSEMBLY.  THESE REPAIRS WILL BE PERFORMED FREE OF CHARGE.  THE RECALL BEGAN ON OCTOBER 23, 2015.  OWNERS MAY CONTACT FORD CUSTOMER SERVICE AT 1-866-436-7332.  FORD'S NUMBER FOR THIS RECALL IS 15S28. ", 'consequence': 'IF THE SHIFT LEVER DISENGAGES FROM THE TRANSMISSION, A DRIVER MAY BE UNABLE TO SHIFT GEAR POSITIONS AND THE INDICATED SHIFT POSITION MAY NOT REPRESENT THE GEAR POSITION THE VEHICLE IS IN.  SHOULD A DISENGAGEMENT OCCUR WHILE THE VEHICLE IS BEING DRIVEN, WHEN THE DRIVER GOES TO STOP AND PARK THE VEHICLE, THE GEAR SELECTION INDICATOR MAY SHOW THAT THE TRANSMISSION IS IN THE "PARK" POSITION, BUT THE VEHICLE TRANSMISSION MAY NOT ACTUALLY BE IN THE "PARK" GEAR POSITION.  IF THE VEHICLE IS NOT IN THE "PARK" POSITION THERE IS A RISK THE VEHICLE WILL ROLL AWAY AS THE DRIVER AND OTHER OCCUPANTS EXIT THE VEHICLE OR ANYTIME THEREAFTER.  A VEHICLE ROLLAWAY INCREASES THE RISK OF INJURY TO EXITING OCCUPANTS AND BYSTANDERS.', 'recall_date': '1/29/2015', 'campaign_number': '15V606000', 'recall_number': '53493'}, {'desc': 'THE TIMKEN COMPANY (TIMKEN) IS RECALLING CERTAIN AFTERMARKET FRONT WHEEL BEARINGS, PART NUMBER 510072, SOLD FROM JANUARY 22, 2015, TO MAY 21, 2015, TO BE USED AS SERVICE PARTS ON 2001-2012 FORD ESCAPE, 2001-2011 MAZDA TRIBUTE, AND 2005-2011 MERCURY MARINER VEHICLES.  THE AFFECTED WHEEL BEARINGS HAVE INCORRECT DIMENSIONS OF A 42MM BORE, 76MM OUTER DIMENSION, AND 39MM WIDTH, INSTEAD OF A 42MM BORE, 78MM OUTER DIMENSION AND A 45MM WIDTH.', 'corrective_action': 'TIMKEN HAS BEGUN NOTIFYING DISTRIBUTORS WHO WILL OFFER PURCHASERS REPLACEMENT WHEEL BEARINGS, FREE OF CHARGE. THE RECALL BEGAN ON MAY 21, 2015.  OWNERS MAY CONTACT TIMKEN CUSTOMER SERVICE AT 1-866-984-6536. ', 'consequence': 'USE OF AN INCORRECTLY SIZED WHEEL BEARING CAN ADVERSELY AFFECT THE BRAKING AND STEERING OF THE VEHICLE, INCREASING THE RISK OF A CRASH.', 'recall_date': '1/3/2015', 'campaign_number': '15E045000', 'recall_number': '53491'}, {'desc': 'FORD MOTOR COMPANY (FORD) IS RECALLING CERTAIN MODEL YEAR 2001-2004 ESCAPE VEHICLES MANUFACTURED OCTOBER 22, 1999, THROUGH JANUARY 23, 2004, ORIGINALLY SOLD, OR CURRENTLY REGISTERED IN, CONNECTICUT, DELAWARE, ILLINOIS, INDIANA, IOWA, MAINE, MARYLAND, MASSACHUSETTS, MICHIGAN, MINNESOTA, MISSOURI, NEW HAMPSHIRE, NEW JERSEY, NEW YORK, OHIO, PENNSYLVANIA, RHODE ISLAND, VERMONT, WEST VIRGINIA, WISCONSIN AND THE DISTRICT OF COLUMBIA.  THESE VEHICLES MAY EXPERIENCE EXCESSIVE CORROSION AT THE FORWARD ATTACHMENT OF THE LOWER CONTROL ARM.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL INSTALL A NEWLY DESIGNED REINFORCEMENT CROSS-BRACE, FREE OF CHARGE.  THE RECALL BEGAN ON MAY 30, 2014.   OWNERS MAY CONTACT FORD AT 1-800-392-3673.  FORD'S NUMBER FOR THIS RECALL IS 14S02.", 'consequence': 'A SEPARATION OF THE LOWER CONTROL ARM CAN RESULT IN A SIGNIFICANT LOSS OF STEERING CONTROL, INCREASING THE RISK OF A CRASH.', 'recall_date': '1/2/2014', 'campaign_number': '14V165000', 'recall_number': '53488'}, {'desc': 'FORD MOTOR COMPANY IS RECALLING CERTAIN MODEL YEAR 2001 THROUGH 2004 ESCAPE VEHICLES EQUIPPED WITH 3.0L V6 ENGINES AND SPEED CONTROL MANUFACTURED FROM OCTOBER 22, 1999, THROUGH JANUARY 23, 2004.  INADEQUATE CLEARANCE BETWEEN THE ENGINE COVER AND THE SPEED CONTROL CABLE CONNECTOR COULD RESULT IN A STUCK THROTTLE WHEN THE ACCELERATOR PEDAL IS FULLY OR ALMOST-FULLY DEPRESSED.  THIS RISK EXISTS REGARDLESS OF WHETHER OR NOT SPEED CONTROL (CRUISE CONTROL) IS USED.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPAIR THE VEHICLES BY INCREASING THE ENGINE COVER CLEARANCE, FREE OF CHARGE.  THE SAFETY RECALL BEGAN AUGUST 3, 2012.  REMEDY PARTS ARE EXPECTED TO BE AVAILABLE IN MID-AUGUST 2012.  UNTIL THEN DEALERS WILL DISCONNECT THE SPEED CONTROL CABLE AS AN INTERIM REMEDY, IF PARTS ARE NOT AVAILABLE AT THE TIME OF AN OWNER'S SERVICE APPOINTMENT.  OWNERS MAY CONTACT FORD AT 1-866-436-7332. ", 'consequence': 'A STUCK THROTTLE MAY RESULT IN VERY HIGH VEHICLE SPEEDS AND MAKE IT DIFFICULT TO STOP OR SLOW THE VEHICLE, WHICH COULD CAUSE A CRASH, SERIOUS INJURY OR DEATH. ', 'recall_date': '1/26/2012', 'campaign_number': '12V353000', 'recall_number': '53489'}, {'desc': 'FORD MOTOR COMPANY IS RECALLING CERTAIN MODEL YEAR 2001 THROUGH 2004 ESCAPE VEHICLES EQUIPPED WITH 3.0L V6 ENGINES AND SPEED CONTROL MANUFACTURED FROM OCTOBER 22, 1999, THROUGH JANUARY 23, 2004.  INADEQUATE CLEARANCE BETWEEN THE ENGINE COVER AND THE SPEED CONTROL CABLE CONNECTOR COULD RESULT IN A STUCK THROTTLE WHEN THE ACCELERATOR PEDAL IS FULLY OR ALMOST-FULLY DEPRESSED.  THIS RISK EXISTS REGARDLESS OF WHETHER OR NOT SPEED CONTROL (CRUISE CONTROL) IS USED.', 'corrective_action': "FORD WILL NOTIFY OWNERS, AND DEALERS WILL REPAIR THE VEHICLES BY INCREASING THE ENGINE COVER CLEARANCE, FREE OF CHARGE.  THE SAFETY RECALL BEGAN AUGUST 3, 2012.  REMEDY PARTS ARE EXPECTED TO BE AVAILABLE IN MID-AUGUST 2012.  UNTIL THEN DEALERS WILL DISCONNECT THE SPEED CONTROL CABLE AS AN INTERIM REMEDY, IF PARTS ARE NOT AVAILABLE AT THE TIME OF AN OWNER'S SERVICE APPOINTMENT.  OWNERS MAY CONTACT FORD AT 1-866-436-7332. ", 'consequence': 'A STUCK THROTTLE MAY RESULT IN VERY HIGH VEHICLE SPEEDS AND MAKE IT DIFFICULT TO STOP OR SLOW THE VEHICLE, WHICH COULD CAUSE A CRASH, SERIOUS INJURY OR DEATH. ', 'recall_date': '1/26/2012', 'campaign_number': '12V353000', 'recall_number': '53490'}, {'desc': 'ON CERTAIN SPORT UTILITY VEHICLES EQUIPPED WITH ANTILOCK BRAKES (ABS), THE ABS MODULE CONNECTOR MAY HAVE MISSING OR DISLODGED WIRE SEALS.  THIS CONDITION COULD ALLOW CONTAMINATION TO ENTER THE MODULE CONNECTOR, CREATING A POTENTIAL FOR AN ELECTRICAL SHORT.  ', 'corrective_action': 'DEALERS WILL INSPECT THE WIRE HARNESS CONNECTOR TO THE ABS MODULE FOR MISSING OR DISLODGED WIRE SEALS, AND REPAIR OR REPLACE THE HARNESS CONNECTOR AS APPROPRIATE.  THE DEALER WILL ALSO INSPECT THE CONNECTOR ON THE ABS MODULE AND REPLACE IT IF IT IS FOUND TO BE CORRODED OR DAMAGED.   THE RECALL BEGAN ON APRIL 23, 2007.  OWNERS MAY CONTACT FORD AT 1-800-392-3673.', 'consequence': 'AN ELECTRICAL SHORT MIGHT CAUSE AN ABS MALFUNCTION THAT WOULD ILLUMINATE THE ABS WARNING LIGHT, AND IN SOME CASES, THE MODULE MAY OVERHEAT RESULTING IN BURNING ODOR, SMOKE, AND/OR FIRE.  THIS CONDITION COULD OCCUR EITHER WHEN THE VEHICLE IGNITION SWITCH IS IN THE OFF POSITION OR WHILE THE VEHICLE IS BEING OPERATED.  ', 'recall_date': '1/10/2007', 'campaign_number': '07V156000', 'recall_number': '53486'}, {'desc': 'CERTAIN CARDONE MASTER CYLINDERS WITH PART NUMBERS 10-2925, 10-2987, 10-2987MZA, 10-3083, 11-3015, 11-3042, 11-3044, 11-3045, 11-3047, 11-3064, AND 11-3156, AND WITH DATE CODES LOWER THAN DCA7078 SOLD AS REPLACEMENT EQUIPMENT FOR USE ON THE VEHICLES LISTED ABOVE.  THE SEAL ON MASTER CYLINDER CAN FAIL AND LEAK BRAKE FLUID.', 'corrective_action': 'CARDONE WILL NOTIFY OWNERS AND OFFER TO REPURCHASE ANY DEFECTIVE MASTER CYLINDERS.  THE RECALL BEGAN DURING APRIL 2007.  OWNERS CAN CONTACT CARDONE AT 1-800-777-4780.', 'consequence': 'LOSS OF BRAKE FLUID CAN RESULT IN POOR BRAKING PERFORMANCE, POSSIBLY RESULTING IN A VEHICLE CRASH.', 'recall_date': '1/29/2007', 'campaign_number': '07E023000', 'recall_number': '53494'}, {'desc': "CERTAIN 2004-2005 SPORT UTILITY VEHICLES AND CERTAIN 2001-2003 SPORT UTIITY VEHICLE HAVING REAR LIFTGATE COMPONENTS SERVICED WITH 2004 EQUIVALENT COMPONENTS FAIL TO COMPLY WITH THE REQUIREMENTS OF FEDERAL MOTOR VEHICLE SAFETY STANDARD NO. 206, 'DOOR LOCKS AND DOOR RETENTION COMPONENTS.'  THE REAR LIFTGATE LATCHING SYSTEM DOES NOT MEET THE INERTIA LOAD REQUIREMENT IN ONE DIRECTION.", 'corrective_action': 'DEALERS WILL REPLACE THE REAR LIFTGATE LATCH RELEASE ROD, THE RELEASE ROD ATTACHMENT CLIP AND THE DOOR HANDLE RETURN SPRING.  THE RECALL BEGAN ON MARCH 31, 2005.  OWNERS SHOULD CONTACT FORD AT 1-800-392-3673.', 'consequence': 'IF THE LIFTGATE IS LEFT UNLOCKED, THERE IS THE POTENTIAL THAT IT MAY OPEN DURING A CRASH.', 'recall_date': '1/20/2004', 'campaign_number': '04V602000', 'recall_number': '53495'}, {'desc': 'ON CERTAIN SPORT UTILITY VEHICLES BUILT WITH 3.0L V6 ENGINES, THE ACCELERATOR CABLE MAY PREVENT THE THROTTLE FROM RETURNING TO THE IDLE POSITION.  ', 'corrective_action': 'DEALERS WILL REPLACE THE ACCELERATOR CABLE.  THE RECALL BEGAN ON JANUARY 10, 2005.  OWNERS SHOULD CONTACT FORD AT 1-866-436-7332.   ', 'consequence': 'AN UNEXPECTED INCREASE IN ENGINE IDLE SPEED MAY INCREASE STOPPING DISTANCE AND MAY RESULT IN A VEHICLE CRASH.  ', 'recall_date': '1/7/2004', 'campaign_number': '04V574000', 'recall_number': '53485'}, {'desc': 'ON CERTAIN SPORT UTILITY VEHICLES EQUIPPED WITH 3.0L V6 ENGINES, DURING DECELERATION, THE ENGINE CAN STALL. ', 'corrective_action': 'DEALERS WILL REPROGRAM THE POWER CONTROL MODULE (PCM) WITH THE APPROPRIATE CALIBRATION.  OWNER NOTIFICATION BEGAN ON APRIL 21, 2004.  OWNERS WHO TAKE THEIR VEHICLES TO AN AUTHORIZED DEALER ON AN AGREED UPON SERVICE DATE AND DO NOT RECEIVE THE FREE REMEDY WITHIN A REASONABLE TIME SHOULD CONTACT FORD AT 1-800-392-3673.', 'consequence': 'SHOULD THE ENGINE STALL, A VEHICLE CRASH COULD OCCUR.', 'recall_date': '1/6/2004', 'campaign_number': '04V165000', 'recall_number': '53487'}]}
recall_example_three = {'message': {'code': 0, 'message': 'ok', 'credentials': 'valid', 'version': 'v3.0.0', 'endpoint': 'recall', 'counter': 8}, 'data': [{'desc': 'HONDA (AMERICAN HONDA MOTOR CO.) IS RECALLING CERTAIN 2016-2018 ACURA MDX, 2015-2019 ACURA TLX AND 2015-2017 HONDA ACCORD VEHICLES, EQUIPPED WITH A 3.5L V6 ENGINE.  PARTICULATES IN FUEL MAY ADHERE TO THE INTERNAL COMPONENTS OF THE FUEL PUMP, REDUCING ITS PERFORMANCE.', 'corrective_action': "HONDA WILL NOTIFY OWNERS, AND DEALERS WILL UPDATE THE FUEL INJECTION ENGINE CONTROL UNIT (FI-ECU) SOFTWARE AND, IF NECESSARY, REPLACE THE FUEL PUMP, FREE OF CHARGE.  THE RECALL BEGAN MARCH 25, 2019.  OWNERS MAY CONTACT CUSTOMER SERVICE AT 1-888-234-2138.  ACURA'S RECALL NUMBER FOR THIS RECALL IS P3W.  HONDA'S RECALL NUMBER FOR THIS RECALL IS N3X.", 'consequence': 'REDUCED FUEL PUMP PERFORMANCE CAN RESULT IN AN ENGINE STALL, INCREASING THE RISK OF CRASH. ', 'recall_date': '1/29/2019', 'campaign_number': '19V060000', 'recall_number': '80711'}]}
recall_responses = [recall_example_one, recall_example_two, recall_example_three] 

# pprint.pprint(recall_example_one)

# come back to GET upcoming repairs
